In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
#  Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a2.shape

(2, 3)

In [6]:
a1.shape

(3,)

In [7]:
a1.size

3

In [8]:
a2.size

6

In [9]:
# number of elements on the array

In [10]:
# Create a Data Frame from a numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Array

In [12]:
n = 5
pi_mat = np.full((n, n), 10)

In [13]:
pi_mat

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [17]:
ones = np.ones((3, 4), dtype = int)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_arr = np.arange(1, 10, 2)
range_arr

array([1, 3, 5, 7, 9])

In [27]:
random_arr = np.random.randint(0, 9, size = (2, 3, 4))

In [28]:
random_arr

array([[[0, 8, 3, 7],
        [4, 0, 7, 3],
        [1, 3, 0, 6]],

       [[1, 6, 0, 7],
        [8, 2, 0, 1],
        [3, 0, 0, 5]]])

## Viewing array and matrices

In [29]:
np.unique(random_arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
a3 = random_arr

In [31]:
a3[0][0][1]

8

In [32]:
# egula age thekei pari

In [35]:
a3[:2, :2, :3]

array([[[0, 8, 3],
        [4, 0, 7]],

       [[1, 6, 0],
        [8, 2, 0]]])

In [37]:
a4 = np.random.randint(10, size = (2, 3, 4, 5))
a4

array([[[[5, 6, 9, 0, 3],
         [1, 3, 0, 4, 3],
         [9, 7, 1, 3, 7],
         [4, 1, 9, 8, 7]],

        [[8, 0, 8, 8, 4],
         [8, 7, 5, 3, 1],
         [1, 7, 6, 2, 9],
         [3, 4, 0, 7, 3]],

        [[6, 0, 9, 0, 6],
         [2, 4, 4, 0, 3],
         [0, 7, 6, 8, 6],
         [9, 0, 4, 1, 8]]],


       [[[9, 4, 9, 1, 0],
         [4, 0, 7, 5, 1],
         [2, 7, 0, 7, 2],
         [7, 4, 9, 3, 0]],

        [[0, 2, 1, 3, 7],
         [1, 9, 3, 8, 5],
         [1, 3, 6, 1, 7],
         [5, 1, 0, 2, 1]],

        [[9, 1, 5, 7, 8],
         [9, 2, 4, 1, 0],
         [1, 2, 8, 9, 2],
         [3, 8, 1, 9, 1]]]])

In [38]:
# Get the first 4 numbers of the inner most array
a4[1][2][0]

array([9, 1, 5, 7, 8])

## Manipulating Arrays

In [40]:
a1

array([1, 2, 3])

In [42]:
ones = np.ones(3)

In [43]:
ones+a1

array([2., 3., 4.])

In [44]:
a1.shape, a2.shape

((3,), (2, 3))

In [45]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [46]:
np.square(a1)

array([1, 4, 9])

## Aggregation
performing the same operation on a number of things

In [47]:
a1

array([1, 2, 3])

In [48]:
a1.sum()

6

In [49]:
np.sum(a1)

6

Tip
Use python's method (sum()) on python datatypes and use numpy's method on numpy
arrays(np.sum())

In [50]:
# big array
big_arr = np.random.random((100000))
big_arr[:30]

array([0.34213627, 0.76124008, 0.922494  , 0.13730552, 0.51268223,
       0.44028207, 0.65905532, 0.57311447, 0.90583156, 0.937856  ,
       0.44749393, 0.09035901, 0.54961414, 0.10697179, 0.70864114,
       0.99010143, 0.15391319, 0.96342094, 0.85071941, 0.15336998,
       0.99646587, 0.20004264, 0.07586112, 0.17723936, 0.99073523,
       0.89488263, 0.96650644, 0.00734454, 0.16946733, 0.94671408])

In [51]:
%timeit sum(big_arr)    # Python's sum()
%timeit np.sum(big_arr) # Numpy's sum()

4.1 ms ± 97.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
20.1 µs ± 15.3 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [52]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [53]:
a2.mean()

3.6333333333333333